config/routes.rb
Rails.application.routes.draw do
  resources :todoitems

  root "todoitems#index"

end

app/models/todoitem.rb
class Todoitem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/todoitems_controller.rb
class TodoitemsController < ApplicationController
  before_action :set_todoitem, only: [:show, :edit, :update, :destroy]

  # GET /todoitems
  # GET /todoitems.json
  def index
    @todoitems = Todoitem.all
  end

  # GET /todoitems/1
  # GET /todoitems/1.json
  def show
  end

  # GET /todoitems/new
  def new
    @todoitem = Todoitem.new
  end

  # GET /todoitems/1/edit
  def edit
  end

  # POST /todoitems
  # POST /todoitems.json
  def create
    @todoitem = Todoitem.new(todoitem_params)

    respond_to do |format|
      if @todoitem.save
        format.html { redirect_to @todoitem, notice: 'Todoitem was successfully created.' }
        format.json { render :show, status: :created, location: @todoitem }
      else
        format.html { render :new }
        format.json { render json: @todoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todoitems/1
  # PATCH/PUT /todoitems/1.json
  def update
    respond_to do |format|
      if @todoitem.update(todoitem_params)
        format.html { redirect_to @todoitem, notice: 'Todoitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @todoitem }
      else
        format.html { render :edit }
        format.json { render json: @todoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todoitems/1
  # DELETE /todoitems/1.json
  def destroy
    @todoitem.destroy
    respond_to do |format|
      format.html { redirect_to todoitems_url, notice: 'Todoitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todoitem
      @todoitem = Todoitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todoitem_params
      params.require(:todoitem).permit(:title, :task)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todoitems_helper.rb
module TodoitemsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">To-Do</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li>
      	<%= link_to new_todoitem_path do%>
      		<span class="glyphicon glyphicon-plus"></span> Task
       	<% end %>
      </li>
      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
 <div class="container">
	<%= yield %>
 </div>

</body>
</html>

app/views/pages/home.html.erb
<h1>To Do</h1>

app/views/todoitems/_form.html.erb
<%= form_for(@todoitem) do |f| %>
  <% if @todoitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todoitem.errors.count, "error") %> prohibited this todoitem from being saved:</h2>

      <ul>
      <% @todoitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="panel panel-default">
  <div class="panel-body">
   
  <div class="form-group">
    <%= f.label :title, "Task Title" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :task, "Task Description" %><br>
    <%= f.text_field :task, size: "60x12" %>
  </div>
  <div class="actions">
    <%= f.submit "Enter", class: "btn btn-primary"%>
  </div>
<% end %>
 
  </div>
</div>

app/views/todoitems/edit.html.erb
<h1>Editing todoitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @todoitem %> |
<%= link_to 'Back', todoitems_path %>

app/views/todoitems/index.html.erb
<h1 class="lead" id="itemsh">Items</h1>
	
<div class="well" id="itemsPanel">
    <% @todoitems.each do |todoitem| %>
    	<div class="row">
    	<div class="col-md-2">
    	<div class="panel panel-default">
    		<div class="panel-heading">
    			<h3 class="panel-title"><%= todoitem.title %></h3>
    		</div>
    	
        <div class="panel-body" id="eachItemPanel">
        	<%= todoitem.task %><br>
       		<div id="del"><%= link_to todoitem, method: :delete, data: { confirm: 'Are you sure?' } do %>
       			<button type="button" class="btn btn-primary">Done</button>      			
       			<%end%>
       		</div>
      	</div>
      	</div>
      	</div>
    <% end %>
</div>
  

app/views/todoitems/new.html.erb
<h1>To Do</h1>

<%= render 'form' %>

<%= link_to 'Back', todoitems_path %>

app/views/todoitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todoitem.title %>
</p>

<p>
  <strong>Task:</strong>
  <%= @todoitem.task %>
</p>

<%= link_to 'Edit', edit_todoitem_path(@todoitem) %> |
<%= link_to 'Back', todoitems_path %>